name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6

      - name: Show specs by URL
        run: npm run demo-find -- --set-gha-outputs

      - name: Show merging of URLs files
        run: npm run demo-merge

      - name: commit updated urls file
        if: github.ref == 'refs/heads/main'
        # https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated urls file
          branch: main
          file_pattern: cypress-visited-urls.json

  release:
    needs: [test]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install everything 📦
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
