name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: cypress-io/github-action@v6

      - name: Show specs by URL sorted by duration
        run: npm run demo-find -- --set-gha-outputs

      - name: Show specs as table and set GHA summary
        run: npm run demo-find -- --set-gha-outputs --table

      - name: Show specs by URL sorted by the number of commands
        run: npm run demo-find-commands

      - name: Show specs as a table (duration)
        run: npm run demo-find-table

      - name: Show specs as a table (commands)
        run: npm run demo-find-table-commands

      - name: Show specs with a cutoff
        run: npm run demo-find-with-cutoff-table-commands

      - name: Show any changes to the URLs file
        run: |
          git status
          git diff cypress-visited-urls.json

      - name: Show merging of URLs files
        run: npm run demo-merge

  release:
    needs: [test]
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install everything 📦
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
